services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-home-energie
    restart: always
    environment:
      MYSQL_DATABASE: home_energy_tracker
    ports:
      - "3307:3307"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mmysql
      - db-data:/var/log/mysql
volumes:
  db-data:
